spring:
  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}
    password: ${REDIS_PASSWORD}
  jackson:
    serialization:
      fail-on-empty-beans: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 111111
    url: jdbc:mysql://localhost:3306/jwt?serverTimezone=Asia/Seoul
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
app:
  name: hyperedu-auth
jwt:
  header: ${JWT_HEADER:Authorization}
  expires_in: ${JWT_EXPIRES_IN:300} # 5 minutes
  secret: ${JWT_SECRET:secret}